openapi: 3.0.0
info:
  version: 2.0.0
  title: Nusantara CMS
  contact:
    name: Gramedia Digital Nusantara
  license:
    name: propietary
servers:
  - url: 'https://bhisma.cloud/api/cms'
paths:
  /page:
    get:
      summary: 'List of user-defined static pages'
      operationId: listPages
      tags:
        - page
      parameters:
        - name: page
          in: query
          description: Pagination option;  The page of results to fetch (1-based).
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            X-Page:
              description: A link to the next page of responses
              schema:
                type: integer
            X-Per-Page:
              description: Maximum number of results per page.
              schema:
                type: integer
            X-Total-Results:
              description: The total number of results across all pages.
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Page:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string